services:
  proxy:
    build:
      context: proxy
    networks:
      - node-nginx
    ports:
      - 8080:80
    depends_on:
      - server

  server:
    build:
      context: server
    ports:
      - "3000:3000"
    entrypoint: /usr/bin/wait-for db:3306 -t 50 -- node src/index.js
    networks:
      - node-nginx
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: node-db-pwd
      MYSQL_DATABASE: node-db
      MYSQL_USER: node-db
      MYSQL_PASSWORD: node-db-pwd
    restart: always
    networks:
      - node-nginx

networks:
  node-nginx:
